### ISSUE TITLE
Stopped working on .107.6 update

### ISSUE THREAD

**Issue by bschatzow** [ljmerza/our-groceries-card#10]
Our groceries no longer working after .107.6 update today.  No problem before.

**Comment by firestrife23** [comment]
same here, there were bunches of errors on logs, complaining about requirements that are version higher than what it's looking for.

**Comment by firestrife23** [comment]
Looked at package.json and it should look like this:

```
"devDependencies": {
	"@babel/cli": ">=7.5.5",
	"@babel/core": ">=7.5.5",
	"@babel/preset-env": ">=7.5.5",
	"babel-loader": ">=8.0.6",
	"eslint": ">=6.0.1",
	"eslint-config-airbnb-base": ">=13.2.0",
	"eslint-plugin-import": ">=2.18.2",
	"webpack": ">=4.36.1",
	"webpack-cli": ">=3.3.6",
	"webpack-merge": ">=4.2.1"
},
```

**Comment by pgsylvestre** [comment]
Same applies to 0.107.7

**Comment by bschatzow** [comment]
Looking at the logs as others have pointed out, the logs show wrong version used on the card build.  Something must have updated in HA requiring a different version.  Did not see anything on it in the breaking changes.
```ERROR: ourgroceries 1.2.3 has requirement aiohttp==3.5.4, but you'll have aiohttp 3.6.1 which is incompatible.
```
One of many.

**Comment by ljmerza** [comment]
HA changed the docker base image so the underlying python library broke. This is hopefully going to be fixed soon

**Comment by bschatzow** [comment]
Still broken for me with the new update.  Component error: ourgroceries - Requirements for ourgroceries not found: ['ourgroceries==1.2.3'].  Is the fix in Home assistant? If so, I'll reach out in the discord /github channels.  I am updating to .108.5.  I'll test again.

**Comment by ljmerza** [comment]
the latest version is 1.3.5

**Comment by bschatzow** [comment]
Core is now at .108.5.  Your card shows 1.4.0 in HACS.

**Comment by ljmerza** [comment]
The latest version of ourgroceries component is 1.3.5 update your component

**Comment by ljmerza** [comment]
with the latest version of the component and card this works for me again on the latest HA

**Comment by bschatzow** [comment]
Doesn't work for me.   
2020-04-17 17:56:48 ERROR (MainThread) [homeassistant.components.hassio] Component error: ourgroceries - Requirements for ourgroceries not found: ['ourgroceries==1.2.3'].
Not sure why it is calling out 1.2.3?  Card version is 1.4.0
Supervisor is 217 and .108.5.  .6 not available to me yet.

**Comment by ljmerza** [comment]
I've already answered this, you need to update your component. The latest version is 1.3.5

**Comment by bschatzow** [comment]
I did.  I'll try an uninstall and reinstall.

**Comment by bschatzow** [comment]
All working again.  Thanks. My confusion is withe the plug-in in HACS and the integration.  They are at different versions.
