### ISSUE TITLE
Enhancement : Automation of update to Shopping List

### ISSUE THREAD

**Issue by nytram-md** [ljmerza/our-groceries-card#14]
Is there a way to send a notification on IOS or Android if there is a change to the list and show that change to the notification ?

Great Addon

Thanks Martyn

**Comment by jampez77** [comment]
You can do this with Node-RED.

**Comment by ljmerza** [comment]
if anyone is interested in this,

**Comment by nytram-md** [comment]
I am interested in how to do this in node red

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
