### ISSUE TITLE
Card does not display the shopping list items

### ISSUE THREAD

**Issue by gekoul** [ljmerza/our-groceries-card#18]
Steps to replicate:
1. Created account on ourgroceries.com
2. Installed ourgroceries integration
2. Istalled ourgroceries lovelace card
3. Added some items on the list through HA, and through OurGroceries web interface.

The number of items on the list is automatically updated on the HA card, nevertheless i see no list (only the number of items).

![image](https://user-images.githubusercontent.com/7930244/114937602-ad75a600-9e46-11eb-897a-5fd925b1cefd.png)

Any ideas are welcome: The card config follows:

type: 'custom:our-groceries-card'
show_header: true
entity: sensor.our_groceries
show_crossed_off: true
sort_by_name: true
hide_empty_lists: 'false,'
show_lists:
  - v2P9PozHrTYKHA7wgyG6DV
icon: 'mdi:format-list-bulleted'

**Comment by atflack** [comment]
Same issues here, different setup config.

![image](https://user-images.githubusercontent.com/78890127/115153779-b1234b80-a045-11eb-8537-9a89fed9c65e.png)

type: 'custom:our-groceries-card'
title: OurGroceries
show_header: true
entity: sensor.our_groceries
show_crossed_off: false
sort_by_name: true
hide_empty_lists: true

**Comment by atflack** [comment]
Resolved here with the update to 1.6.1, thanks!
