### ISSUE TITLE
Add/Remove Items

### ISSUE THREAD

**Issue by frelev** [ljmerza/our-groceries-card#5]
Reading adding/removing items should now be possible from 1.2 but I cannot find how to use this functionality. Where should this option appear?

I´ve updated both component and card to latest version

**Comment by ljmerza** [comment]
there should be a plus sign next to the list name. If not and you're sure you have the latest version try clearing your cache

**Comment by frelev** [comment]
Thanks
See it now on my mobile at least so it seems to be cache related
