### ISSUE TITLE
filter shown lists

### ISSUE THREAD

**Issue by ljmerza** [ljmerza/our-groceries-card#7]
add filter option

```yaml
filter:
 include: regex
 exclude: regex
```

**Comment by zvenberg** [comment]
Is it possible to get a filter or option to only show lists with items, and not show the empty lists in the card?
`show_empty: false`

**Comment by jesse-projects** [comment]
Oh man, I was trying to use the "entity" option to drill down to something line sensor.our_groceries.XXXXXX where XXXXX was the sensor "ID" for the list. This would be a VERY helpful feature!

**Comment by Stefan-OJ** [comment]
Also need this, please!

**Comment by jampez77** [comment]
I've put in a PR for these kind of changes.

https://github.com/ljmerza/our-groceries-card/pull/16

It includes:

`show_empty` as detailed above
`show_lists` allows you to specify which lists are shown (using the list IDs)

**Comment by ljmerza** [comment]
added in v1.6.0 via

```
hide_empty_lists: true
show_lists:
  - listid
```
